openapi: 3.0.0
info:
  title: Corp Messenger API
  version: 1.0.0
  description: Retrieve and send messages
servers:
  - url: 'http://messenger.rostkov.me/api'
    description: Продуктовый сервер
  - url: 'http://beta.messenger.rostkov.me/api'
    description: Тестовый сервер
paths:
  /auth/register:
    post:
      requestBody:
        description: Данные для регистрации нового пользователя
        content:
          application/json:
            schema:
              type: object
              required:
                - login
                - password
                - first_name
                - middle_name
                - last_name
                - company_id
              properties:
                login:
                  type: string
                  description: Имя пользователя
                password:
                  type: string
                  description: Пароль
                first_name:
                  type: string
                  description: Имя
                middle_name:
                  type: string
                  description: Отчество
                last_name:
                  type: string
                  description: Фамилия
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInstance'
              examples:
                Example 1:
                  value:
                    id: 0
                    login: Steve
                    first_name: Steve
                    middle_name: Paul
                    last_name: Jobs
                    company:
                      id: 1
                      name: Apple
                    img_url: string
                    is_online: true
          description: Пользователь успешно зарегистрирован
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Пользователь с таким username уже существует
      operationId: registerUser
      tags:
        - auth
      summary: Регистрация нового пользователя
      description: Регистрация нового пользователя в системе
      security: []
  /auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
            examples:
              Example 1:
                value:
                  login: Steve
                  password: qwerty
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    $ref: '#/components/schemas/Tokens'
                    description: Токены для доступа к API
                  user:
                    $ref: '#/components/schemas/UserInstance'
                    description: Данные пользователя
              examples:
                Example 1:
                  value:
                    token:
                      accessToken: 73d65aec-8431-447f-a163-1c1838b51d82
                      refreshToken: 786e91a0-1be4-4328-96f7-3539bbbfa9f9
                    user:
                      id: 0
                      login: Steve
                      first_name: Steve
                      middle_name: Paul
                      last_name: Jobs
                      company:
                        id: 1
                        name: Apple
                      img_url: string
                      is_online: true
          description: Авторизация прошла успешно
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный логин или пароль
      operationId: loginUser
      tags:
        - auth
      summary: Авторизация
      description: Авторизация пользователя в системе и получение токена
      security: []
  /auth/renew:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
                  description: Токен для обновления
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
              examples:
                Example 1:
                  value:
                    accessToken: 73d65aec-8431-447f-a163-1c1838b51d82
                    refreshToken: 786e91a0-1be4-4328-96f7-3539bbbfa9f9
          description: Токен обновлен
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен обновления
      operationId: renewToken
      tags:
        - auth
      summary: Обновление токена
      description: Обновление токена доступа
  /chats:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chats'
              examples:
                Example 1:
                  value:
                    - id: 0
                      name: Разработчики
                      img_url: 'https://picsum.photos/200'
                      company_id: 1
                      unread: 12
                      last_message:
                        id: 2456
                        parent_id: 0
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        text: Всем привет
                        user_id: 2
                        chat_id: 1
                        is_pinned: true
                        is_read: true
                        attachments:
                          - id: 0
                            created_at: '2019-08-24T14:15:22Z'
                            type: image
                            url: 'https://picsum.photos/200'
                            thumbnail_url: 'https://picsum.photos/200'
                            size: 0
                            name: photo.jpeg
                      is_pinned: true
                      is_private: true
                      type: group
          description: Список чатов
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
      operationId: getChats
      tags:
        - chats
      summary: Получение списка чатов
      description: Получение списка чатов пользователя
    post:
      requestBody:
        description: Данные для создания нового чата
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
            examples:
              Example 1:
                value:
                  id: 0
                  name: string
                  company_id: 0
                  is_pinned: true
                  is_private: true
                  img_url: string
                  type: group
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
          description: Чат успешно создан
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
      operationId: createChat
      tags:
        - chats
      summary: Создание нового чата
      description: Создание нового чата
  '/chat/{chatId}':
    get:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  chat:
                    $ref: '#/components/schemas/Chat'
                    description: Данные чата
                  members:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserInstance'
                    description: Список участников чата
              examples:
                Example 1:
                  value:
                    chat:
                      id: 1
                      name: Общий чат
                      company_id: 1
                      is_pinned: true
                      is_private: true
                      img_url: 'https://picsum.photos/200'
                      type: group
                    members:
                      - id: 0
                        login: string
                        first_name: Steve
                        middle_name: Paul
                        last_name: Jobs
                        company:
                          id: 1
                          name: string
                        img_url: 'https://picsum.photos/200'
                        is_online: true
          description: Информация о чате
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: getChat
      tags:
        - chat
      summary: Получение информации о чате
      description: Получение информации о чате
    post:
      requestBody:
        description: Данные для обновления информации о чате
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatInstance'
        required: true
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatInstance'
          description: Информация о чате успешно обновлена
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: updateChat
      tags:
        - chat
      summary: Обновление информации о чате
      description: Обновление информации о чате
    delete:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatInstance'
          description: Чат успешно удален
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: deleteChat
      tags:
        - chat
      summary: Удаление чата
      description: Удаление чата
  '/chat/{chatId}/leave':
    post:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
              examples:
                Example 1:
                  value:
                    id: 1
                    name: Общий чат
                    company_id: 1
                    is_pinned: true
                    is_private: true
                    img_url: 'https://picsum.photos/200'
                    type: group
          description: Пользователь успешно покинул чат
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: leaveChat
      tags:
        - chat
      summary: Покинуть чат
      description: Покинуть чат
  '/chat/{chatId}/member/{userId}':
    post:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
        - name: userId
          description: Идентификатор пользователя
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Chat'
                  - type: object
                    properties:
                      members_count:
                        type: integer
                        description: Количество участников чата
                        example: 1
              examples:
                Example 1:
                  value:
                    id: 1
                    name: Общий чат
                    company_id: 1
                    is_pinned: true
                    is_private: true
                    img_url: 'https://picsum.photos/200'
                    type: group
                    members_count: 1
          description: Пользователь успешно приглашен в чат
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: inviteUser
      tags:
        - chat
      summary: Приглашение пользователя в чат
      description: Приглашение пользователя в чат
    delete:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
        - name: userId
          description: Идентификатор пользователя
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatInstance'
          description: Пользователь успешно исключен из чата
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: kickUser
      tags:
        - chat
      summary: Исключение пользователя из чата
      description: Исключение пользователя из чата
  '/chat/{chatId}/pin':
    post:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatInstance'
              examples:
                Example 1:
                  value:
                    id: 1
                    name: Общий чат
                    img_url: 'https://picsum.photos/200'
                    company_id: 1
                    unread: 0
                    last_message:
                      id: 1
                      parent_id: 0
                      created_at: '2019-08-24T14:15:22Z'
                      updated_at: '2019-08-24T14:15:22Z'
                      text: Все
                      user_id: 1
                      chat_id: 1
                      is_pinned: true
                      is_read: true
                      attachments:
                        - id: 1
                          created_at: '2019-08-24T14:15:22Z'
                          type: image
                          url: 'https://picsum.photos/200'
                          thumbnail_url: 'https://picsum.photos/200'
                          size: 1
                          name: image.jpeg
                      event:
                        id: 1
                        created_at: '2019-08-24T14:15:22Z'
                        type: user_joined
                        message_id: 1
                        payload: '{}'
                    is_pinned: true
                    is_private: true
                    type: group
          description: Чат успешно закреплен
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: pinChatMessage
      tags:
        - chat
      summary: Закрепление чата
      description: 'Закрепление чата в списке чатов, чтобы он всегда был вверху'
    delete:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatInstance'
          description: Чат успешно откреплен
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: unpinChatMessage
      tags:
        - chat
      summary: Открепление чата
      description: Открепление чата из списка чатов
  '/chat/{chatId}/messages':
    get:
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
        - name: count
          description: 'Количество сообщений, которое необходимо получить. Если указан startMessageId и count < 0, \ то startMessageId будет включён в выборку'
          schema:
            type: integer
          in: query
          required: false
        - name: startMessageId
          description: 'Идентификатор сообщения, с которого необходимо начать получение'
          schema:
            type: integer
          in: query
          required: false
      responses:
        '200':
          description: Список сообщений чата
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    minItems: 2
                    maxItems: 20
                    items:
                      $ref: '#/components/schemas/Message'
                  users:
                    type: array
                    minItems: 1
                    maxItems: 20
                    items:
                      $ref: '#/components/schemas/UserInstance'
              examples:
                Example 1:
                  value:
                    messages:
                      - id: 1
                        parent_id: 0
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        text: Все
                        user_id: 1
                        chat_id: 1
                        is_pinned: true
                        is_read: true
                        attachments:
                          - id: 1
                            created_at: '2019-08-24T14:15:22Z'
                            type: image
                            url: 'https://picsum.photos/200'
                            thumbnail_url: 'https://picsum.photos/200'
                            size: 1
                            name: image.jpeg
                        event:
                          id: 1
                          created_at: '2019-08-24T14:15:22Z'
                          type: user_joined
                          message_id: 1
                          payload: '{}'
                    users:
                      - id: 0
                        login: string
                        first_name: Steve
                        middle_name: Paul
                        last_name: Jobs
                        company:
                          id: 1
                          name: string
                        img_url: 'https://picsum.photos/200'
                        is_online: true
                Example 3:
                  value:
                    messages:
                      - id: 1
                        parent_id: 0
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        text: Все
                        user_id: 1
                        chat_id: 1
                        is_pinned: true
                        is_read: true
                        attachments:
                          - id: 1
                            created_at: '2019-08-24T14:15:22Z'
                            type: image
                            url: 'https://picsum.photos/200'
                            thumbnail_url: 'https://picsum.photos/200'
                            size: 1
                            name: image.jpeg
                        event:
                          id: 1
                          created_at: '2019-08-24T14:15:22Z'
                          type: user_joined
                          message_id: 1
                          payload: '{}'
                      - id: 1
                        parent_id: 0
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        text: Все
                        user_id: 1
                        chat_id: 1
                        is_pinned: true
                        is_read: true
                        attachments:
                          - id: 1
                            created_at: '2019-08-24T14:15:22Z'
                            type: image
                            url: 'https://picsum.photos/200'
                            thumbnail_url: 'https://picsum.photos/200'
                            size: 1
                            name: image.jpeg
                        event:
                          id: 1
                          created_at: '2019-08-24T14:15:22Z'
                          type: user_joined
                          message_id: 1
                          payload: '{}'
                    users:
                      - id: 0
                        login: string
                        first_name: Steve
                        middle_name: Paul
                        last_name: Jobs
                        company:
                          id: 1
                          name: string
                        img_url: 'https://picsum.photos/200'
                        is_online: true
                Example 2:
                  value:
                    messages:
                      - id: 1
                        parent_id: 0
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        text: Все
                        user_id: 1
                        chat_id: 1
                        is_pinned: true
                        is_read: true
                        attachments:
                          - id: 1
                            created_at: '2019-08-24T14:15:22Z'
                            type: image
                            url: 'https://picsum.photos/200'
                            thumbnail_url: 'https://picsum.photos/200'
                            size: 1
                            name: image.jpeg
                        event:
                          id: 1
                          created_at: '2019-08-24T14:15:22Z'
                          type: user_joined
                          message_id: 1
                          payload: '{}'
                      - id: 1
                        parent_id: 0
                        created_at: '2019-08-24T14:15:22Z'
                        updated_at: '2019-08-24T14:15:22Z'
                        text: Все
                        user_id: 1
                        chat_id: 1
                        is_pinned: true
                        is_read: true
                        attachments:
                          - id: 1
                            created_at: '2019-08-24T14:15:22Z'
                            type: image
                            url: 'https://picsum.photos/200'
                            thumbnail_url: 'https://picsum.photos/200'
                            size: 1
                            name: image.jpeg
                        event:
                          id: 1
                          created_at: '2019-08-24T14:15:22Z'
                          type: user_joined
                          message_id: 1
                          payload: '{}'
                    users:
                      - id: 0
                        login: string
                        first_name: Steve
                        middle_name: Paul
                        last_name: Jobs
                        company:
                          id: 1
                          name: string
                        img_url: 'https://picsum.photos/200'
                        is_online: true
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: getChatMessages
      tags:
        - messages
      summary: Получение списка сообщений чата
      description: Получение списка сообщений чата
    post:
      requestBody:
        description: Данные для создания нового сообщения
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      parameters:
        - name: chatId
          description: Идентификатор чата
          schema:
            type: integer
          in: path
          required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: Сообщение успешно создано
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Чат не найден
      operationId: createMessage
      tags:
        - messages
      summary: Создание нового сообщения
      description: Создание нового сообщения
  '/message/{messageId}':
    delete:
      parameters:
        - name: messageId
          description: Идентификатор сообщения
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
              examples: {}
          description: Сообщение успешно удалено
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Сообщение не найдено
      operationId: deleteMessage
      tags:
        - messages
      summary: Удаление сообщения
      description: Удаление сообщения
  '/message/{messageId}/edit':
    post:
      requestBody:
        description: Данные для редактирования сообщения
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
            examples:
              Example 1:
                value:
                  id: 1
                  parent_id: 0
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                  text: Все
                  user_id: 1
                  chat_id: 1
                  is_pinned: true
                  is_read: true
                  attachments:
                    - id: 1
                      created_at: '2019-08-24T14:15:22Z'
                      type: image
                      url: 'https://picsum.photos/200'
                      thumbnail_url: 'https://picsum.photos/200'
                      size: 1
                      name: image.jpeg
                  event:
                    id: 1
                    created_at: '2019-08-24T14:15:22Z'
                    type: user_joined
                    message_id: 1
                    payload: '{}'
        required: true
      parameters:
        - name: messageId
          description: Идентификатор сообщения
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              examples:
                Example 1:
                  value:
                    id: 1
                    parent_id: 0
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    text: Все
                    user_id: 1
                    chat_id: 1
                    is_pinned: true
                    is_read: true
                    attachments:
                      - id: 1
                        created_at: '2019-08-24T14:15:22Z'
                        type: image
                        url: 'https://picsum.photos/200'
                        thumbnail_url: 'https://picsum.photos/200'
                        size: 1
                        name: image.jpeg
                    event:
                      id: 1
                      created_at: '2019-08-24T14:15:22Z'
                      type: user_joined
                      message_id: 1
                      payload: '{}'
          description: Сообщение успешно отредактировано
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Сообщение не найдено
      operationId: editMessage
      tags:
        - messages
      summary: Редактирование сообщения
      description: Редактирование сообщения
  '/message/{messageId}/pin':
    post:
      parameters:
        - name: messageId
          description: Идентификатор сообщения
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              examples:
                Example 1:
                  value:
                    id: 1
                    parent_id: 0
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
                    text: Все
                    user_id: 1
                    chat_id: 1
                    is_pinned: true
                    is_read: true
                    attachments:
                      - id: 1
                        created_at: '2019-08-24T14:15:22Z'
                        type: image
                        url: 'https://picsum.photos/200'
                        thumbnail_url: 'https://picsum.photos/200'
                        size: 1
                        name: image.jpeg
                    event:
                      id: 1
                      created_at: '2019-08-24T14:15:22Z'
                      type: user_joined
                      message_id: 1
                      payload: '{}'
          description: Сообщение успешно закреплено
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Сообщение не найдено
      operationId: pinMessage
      tags:
        - messages
      summary: Закрепление сообщения
      description: Закрепление сообщения
    delete:
      parameters:
        - name: messageId
          description: Идентификатор сообщения
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: Сообщение успешно откреплено
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Сообщение не найдено
      operationId: unpinMessage
      tags:
        - messages
      summary: Открепление сообщения
      description: Открепление сообщения
  /messages/read:
    post:
      requestBody:
        description: Данные для отметки сообщений прочитанными
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
              examples: {}
          description: Сообщения успешно отмечены прочитанными
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
      operationId: readMessages
      tags:
        - messages
      summary: Отметка сообщений прочитанными
      description: Отметка сообщений прочитанными
  /search:
    post:
      operationId: search
      tags:
        - search
      summary: Поиск сообщений и чатов
      description: Поиск по названиям чатов и сообщениям
      requestBody:
        description: Поисковый запрос
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Поисковый запрос части сообщения или названия чата
                  minLength: 3
                  maxLength: 256
                  example: Привет
        required: true
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
              examples:
                Example 1:
                  value:
                    message: string
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
  /search/users:
    post:
      operationId: searchUsers
      tags:
        - search
      summary: Поиск пользователей
      description: Поиск пользователей по ФИО
      requestBody:
        description: Поисковый запрос
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Поисковый запрос части ФИО пользователя
                  minLength: 3
                  maxLength: 256
                  example: Иванов
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
              examples:
                Example 1:
                  value:
                    - id: 0
                      login: string
                      first_name: Steve
                      middle_name: Paul
                      last_name: Jobs
                      company:
                        id: 1
                        name: string
                      img_url: 'https://picsum.photos/200'
                      is_online: true
          description: Результаты поиска
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
  '/user/{id}':
    get:
      parameters:
        - name: id
          description: Идентификатор пользователя
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInstance'
              examples:
                Example 1:
                  value:
                    id: 0
                    login: string
                    first_name: Steve
                    middle_name: Paul
                    last_name: Jobs
                    company:
                      id: 1
                      name: string
                    img_url: 'https://picsum.photos/200'
                    is_online: true
          description: Пользователь успешно найден
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Пользователь не найден
      operationId: getUser
      tags:
        - users
      summary: Получение пользователя
      description: Получение пользователя по идентификатору
    post:
      parameters:
        - name: id
          description: Идентификатор пользователя
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInstance'
          description: Пользователь успешно обновлен
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректные данные
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Неверный токен доступа
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Нет прав на изменение пользователя
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Пользователь не найден
      operationId: updateUser
      tags:
        - users
      summary: Обновление пользователя
      description: Обновление пользователя по идентификатору
      requestBody:
        description: Данные пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInstance'
        required: true
components:
  schemas:
    Tokens:
      type: object
      properties:
        accessToken:
          description: Токен доступа
          type: string
          format: uuid
        refreshToken:
          description: Токен обновления
          type: string
          format: uuid
    User:
      type: object
      x-examples:
        Example 1:
          id: 123
          username: Steve
          password: pa$$word
          company_id: 21
      properties:
        id:
          format: int64
          type: integer
          minimum: 1
        username:
          type: string
          example: Steve
          minLength: 2
          maxLength: 32
        password:
          format: password
          type: string
        company_id:
          format: string
          description: 'ID компании, к которой принадлежит пользователь (шестнадцатеричный UUID)'
          type: integer
          example: 21
          minimum: 1
      required:
        - username
        - password
    UserInstance:
      type: object
      properties:
        id:
          format: int64
          type: integer
        login:
          type: string
          minLength: 1
        first_name:
          type: string
          example: Steve
          minLength: 1
        middle_name:
          type: string
          example: Paul
          minLength: 0
        last_name:
          type: string
          example: Jobs
          minLength: 1
        company:
          $ref: '#/components/schemas/Company'
        img_url:
          type: string
          format: url
          example: 'https://picsum.photos/200'
        is_online:
          type: boolean
      required:
        - first_name
        - last_name
        - company
      x-examples:
        Example 1:
          id: -9223372036854776000
          login: string
          first_name: Steve
          middle_name: Paul
          last_name: Jobs
          company:
            id: 0
            name: string
          img_url: 'https://picsum.photos/200'
          is_online: true
    Users:
      type: array
      items:
        $ref: '#/components/schemas/UserInstance'
      x-examples:
        Example 1:
          - id: 0
            login: string
            first_name: Steve
            middle_name: Paul
            last_name: Jobs
            company:
              id: 0
              name: string
            img_url: 'https://picsum.photos/200'
            is_online: true
    Company:
      type: object
      properties:
        id:
          format: int64
          type: integer
          minimum: 1
        name:
          type: string
      required:
        - name
      x-examples:
        Example 1:
          id: 1
          name: Apple
    Chat:
      description: Краткая информация о чате для заполнения
      type: object
      x-examples:
        Example 1:
          id: 1
          name: Общий чат
          company_id: 1
          is_pinned: true
          is_private: true
          img_url: 'https://picsum.photos/200'
          type: group
      properties:
        id:
          format: int64
          type: integer
          minimum: 1
        name:
          type: string
          minLength: 1
          example: Общий чат
        company_id:
          format: string
          description: 'ID компании, к которой принадлежит чат (шестнадцатеричный UUID)'
          type: integer
          example: 1
          minimum: 1
        is_pinned:
          type: boolean
          description: 'Признак того, что чат закреплен'
        is_private:
          type: boolean
          description: 'Признак того, что чат приватный (тет-а-тет)'
        img_url:
          type: string
          format: url
          description: Ссылка на изображение чата
          example: 'https://picsum.photos/200'
        type:
          type: string
          description: Тип чата
          enum:
            - group
            - private
            - channel
            - conference
      required:
        - name
    Chats:
      description: Список чатов
      type: array
      items:
        $ref: '#/components/schemas/ChatInstance'
      x-examples:
        Example 1:
          - id: 1
            name: Общий чат
            img_url: 'https://picsum.photos/200'
            company_id: 1
            unread: 0
            last_message:
              id: 1
              parent_id: 0
              created_at: '2019-08-24T14:15:22Z'
              updated_at: '2019-08-24T14:15:22Z'
              text: Все
              user_id: 1
              chat_id: 1
              is_pinned: true
              is_read: true
              attachments:
                - id: 1
                  created_at: '2019-08-24T14:15:22Z'
                  type: image
                  url: 'https://picsum.photos/200'
                  thumbnail_url: 'https://picsum.photos/200'
                  size: 1
                  name: image.jpeg
              event:
                id: 1
                created_at: '2019-08-24T14:15:22Z'
                type: user_joined
                message_id: 1
                payload: '{}'
            is_pinned: true
            is_private: true
            type: group
      title: ''
    ChatInstance:
      description: 'Полная информация о чате, включая список участников'
      type: object
      properties:
        id:
          format: int64
          type: integer
          minimum: 1
        name:
          type: string
          example: Общий чат
        img_url:
          type: string
          format: url
          description: 'URL изображения чата или профиля пользователя. Если нет изображения, то null'
          example: 'https://picsum.photos/200'
        company_id:
          format: string
          description: 'ID компании, к которой принадлежит чат (шестнадцатеричный UUID)'
          type: integer
          minimum: 1
          example: 1
        unread:
          type: integer
        last_message:
          $ref: '#/components/schemas/Message'
        is_pinned:
          type: boolean
          description: 'Признак того, что чат закреплен'
        is_private:
          type: boolean
          description: 'Признак того, что чат приватный (тет-а-тет)'
        type:
          type: string
          description: Тип чата
          enum:
            - group
            - private
            - channel
            - conference
      required:
        - name
      x-examples:
        Example 1:
          id: 1
          name: Общий чат
          img_url: 'https://picsum.photos/200'
          company_id: 1
          unread: 0
          last_message:
            id: 1
            parent_id: 0
            created_at: '2019-08-24T14:15:22Z'
            updated_at: '2019-08-24T14:15:22Z'
            text: Все
            user_id: 1
            chat_id: 1
            is_pinned: true
            is_read: true
            attachments:
              - id: 1
                created_at: '2019-08-24T14:15:22Z'
                type: image
                url: 'https://picsum.photos/200'
                thumbnail_url: 'https://picsum.photos/200'
                size: 1
                name: image.jpeg
            event:
              id: 1
              created_at: '2019-08-24T14:15:22Z'
              type: user_joined
              message_id: 1
              payload: '{}'
          is_pinned: true
          is_private: true
          type: group
    Error:
      required:
        - message
      type: object
      properties:
        message:
          description: A human readable error message
          type: string
    UserCredentials:
      description: Данные для авторизации пользователя
      type: object
      x-examples:
        Example 1:
          login: Steve
          password: pa$$word
      properties:
        login:
          description: Имя пользователя
          type: string
          example: Steve
        password:
          description: Пароль пользователя
          type: string
          format: password
      required:
        - login
        - password
    Message:
      description: Сообщение
      type: object
      properties:
        id:
          format: int64
          type: integer
          minimum: 1
        parent_id:
          format: int64
          type: integer
          minimum: 0
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
        text:
          type: string
          example: Все
        user_id:
          format: int64
          type: integer
          minimum: 1
        chat_id:
          format: int64
          type: integer
          minimum: 1
        is_pinned:
          type: boolean
        is_read:
          type: boolean
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        event:
          $ref: '#/components/schemas/Event'
      required:
        - id
        - text
        - user_id
        - chat_id
      x-examples:
        Example 1:
          id: 1
          parent_id: 0
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
          text: Все
          user_id: 1
          chat_id: 1
          is_pinned: true
          is_read: true
          attachments:
            - id: 1
              created_at: '2019-08-24T14:15:22Z'
              type: image
              url: 'https://picsum.photos/200'
              thumbnail_url: 'https://picsum.photos/200'
              size: 1
              name: image.jpeg
          event:
            id: 1
            created_at: '2019-08-24T14:15:22Z'
            type: user_joined
            message_id: 1
            payload: '{}'
    Attachment:
      description: Вложение
      type: object
      x-examples:
        Example 1:
          id: 1
          created_at: '2019-08-24T14:15:22Z'
          type: image
          url: 'https://picsum.photos/200'
          thumbnail_url: 'https://picsum.photos/200'
          size: 1
          name: image.jpeg
      properties:
        id:
          format: int64
          type: integer
          minimum: 1
        created_at:
          format: date-time
          type: string
        type:
          enum:
            - image
            - video
            - audio
            - file
        url:
          type: string
          format: uri
          example: 'https://picsum.photos/200'
        thumbnail_url:
          type: string
          format: url
          example: 'https://picsum.photos/200'
        size:
          format: int64
          type: integer
          description: Размер вложения в байтах
          minimum: 1
          maximum: 1000000
          exclusiveMaximum: false
        name:
          type: string
          example: image.jpeg
      required:
        - type
        - url
    Event:
      description: Событие
      type: object
      x-examples:
        Example 1:
          id: 1
          created_at: '2019-08-24T14:15:22Z'
          type: user_joined
          message_id: 1
          payload: '{}'
      properties:
        id:
          format: int64
          type: integer
          minimum: 1
        created_at:
          format: date-time
          type: string
        type:
          enum:
            - user_joined
            - user_left
            - chat_created
            - chat_updated
            - chat_deleted
            - chat_renamed
            - chat_avatar_updated
            - chat_avatar_deleted
            - chat_description_updated
            - chat_description_deleted
            - chat_user_added
            - chat_user_removed
        message_id:
          format: int64
          type: integer
          minimum: 1
        payload:
          type: string
          format: json-pointer
          example: '{}'
      required:
        - created_at
        - type
        - message_id
    Messages:
      description: Список сообщений
      type: array
      items:
        $ref: '#/components/schemas/Message'
      x-examples:
        Example 1:
          - id: 1
            parent_id: 0
            created_at: '2019-08-24T14:15:22Z'
            updated_at: '2019-08-24T14:15:22Z'
            text: Все
            user_id: 1
            chat_id: 1
            is_pinned: true
            is_read: true
            attachments:
              - id: 1
                created_at: '2019-08-24T14:15:22Z'
                type: image
                url: 'https://picsum.photos/200'
                thumbnail_url: 'https://picsum.photos/200'
                size: 1
                name: image.jpeg
            event:
              id: 1
              created_at: '2019-08-24T14:15:22Z'
              type: user_joined
              message_id: 1
              payload: '{}'
    SearchResult:
      description: Результаты поиска
      type: object
      x-examples:
        Example 1:
          chats:
            - id: 1
              name: Общий чат
              img_url: 'https://picsum.photos/200'
              company_id: 1
              unread: 0
              last_message:
                id: 1
                parent_id: 0
                created_at: '2019-08-24T14:15:22Z'
                updated_at: '2019-08-24T14:15:22Z'
                text: Все
                user_id: 1
                chat_id: 1
                is_pinned: true
                is_read: true
                attachments:
                  - id: 1
                    created_at: '2019-08-24T14:15:22Z'
                    type: image
                    url: 'https://picsum.photos/200'
                    thumbnail_url: 'https://picsum.photos/200'
                    size: 1
                    name: image.jpeg
                event:
                  id: 1
                  created_at: '2019-08-24T14:15:22Z'
                  type: user_joined
                  message_id: 1
                  payload: '{}'
              is_pinned: true
              is_private: true
              type: group
          messages:
            - id: 1
              parent_id: 0
              created_at: '2019-08-24T14:15:22Z'
              updated_at: '2019-08-24T14:15:22Z'
              text: Все
              user_id: 1
              chat_id: 1
              is_pinned: true
              is_read: true
              attachments:
                - id: 1
                  created_at: '2019-08-24T14:15:22Z'
                  type: image
                  url: 'https://picsum.photos/200'
                  thumbnail_url: 'https://picsum.photos/200'
                  size: 1
                  name: image.jpeg
              event:
                id: 1
                created_at: '2019-08-24T14:15:22Z'
                type: user_joined
                message_id: 1
                payload: '{}'
      properties:
        chats:
          type: array
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/ChatInstance'
        messages:
          type: array
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/Message'
    Success:
      description: Успешный ответ
      type: object
      properties:
        success:
          type: boolean
  securitySchemes:
    AccessToken:
      type: apiKey
      name: AccessToken
      in: header
security:
  - AccessToken: []
